# Generated by Django 5.0.8 on 2024-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='question_text',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='draft', max_length=10),
        ),
    ]
