# Generated by Django 5.0.8 on 2024-08-22 11:39

import django.utils.timezone
import news.custom_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', news.custom_field.CustomBooleanField(default=False)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('admin_message', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
