# Generated by Django 5.0.8 on 2024-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='admin_message',
            field=models.TextField(default='', max_length=500),
        ),
    ]
