# Generated by Django 5.0.8 on 2024-09-28 13:19

import news.custom_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_contact_admin_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='admin_message',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=news.custom_field.CustomBooleanField(choices=[(True, 'Contacted'), (False, 'Not contacted yet')], default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
