# Generated by Django 5.0.8 on 2024-10-03 13:00

import django.db.models.deletion
import news.helpers
import shop.custom_field
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_homepage', shop.custom_field.CustomBooleanField(default=False)),
                ('status', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='PlantingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Planting Method',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('ordering', models.IntegerField(default=0)),
                ('special', shop.custom_field.CustomBooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_sale', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_real', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_sold', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to=news.helpers.get_file_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('planting_methods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.plantingmethod')),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
    ]
