# Generated by Django 5.0.8 on 2024-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='planting_methods',
        ),
        migrations.AddField(
            model_name='product',
            name='planting_methods',
            field=models.ManyToManyField(to='shop.plantingmethod'),
        ),
    ]
