# Generated by Django 5.0.8 on 2024-10-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options_alter_product_price_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
